name: Rotate AWS keys

on:
  push:

jobs:
  rotate:
    name: rotate iam user keys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
        
      - name: rotate aws keys
        uses: ./
        env:
          AWS_ACCESS_KEY_ID: ${{secret  }}
          AWS_SECRET_ACCESS_KEY: ${{secret }}
          IAM_USERNAME: 'username'
          GITHUB_TOKEN: ${{token }}
          OWNER_REPOSITORY: ${{ github.repository }}
